### ISSUE TITLE
we need more patterns

### ISSUE THREAD

**Issue by bazera** [Tchanu/design-patterns#1]
please provide us with more patterns!

**Comment by Tchanu** [comment]
I really appreciate your interest and support. I will keep adding more patterns as soon as I get a chance. Remember, PRs are welcome!

**Comment by Tchanu** [comment]
Hey. Good news! After 5 months of inactivity, I've added a [Prototype Pattern](https://github.com/Tchanu/design-patterns/tree/master/examples). Check it out!
I am happy to close this issue.

**Comment by Tchanu** [comment]
Okay, I will add more.

**Comment by Tchanu** [comment]
[Merge pull request #2 from Tchanu/pattern-prototype](https://github.com/Tchanu/design-patterns/commit/946649ab86ad900a229956716c32ba35dcf0d323)
